development:
  adapter: postgresql
  database: sampleapp
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sampleapp
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sampleapp
  host: localhost
  pool: 5
  timeout: 5000
